### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by frmichel** [lod-cloud/lod-cloud-site#2]
Hey @jmccrae, I've just installed the application but I cannot manage to authenticate to submit or update a dataset.
When I click on submit, I get the "Login required" page, I select "Sign in with google", then I get an error from https://accounts.google.com/signin/oauth/error saying : 

    Error 400 : invalid_request
    Invalid parameter value for redirect_uri: Missing scheme: null

At the same time, the application console displays an exception:
```
java.io.FileNotFoundException: oauth2 (Le fichier spécifié est introuvable)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at org.insightcentre.lodcloud.Authorize.<clinit>(Authorize.java:25)
        at org.insightcentre.lodcloud.DatasetAdd.doGet(DatasetAdd.java:48)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        (...)

```

What is this oauth2 file? Should it be provided or obtained prior to running?

**Comment by jmccrae** [comment]
`oauth2` is a secret file that authenticates the site with Google. It needs to be obtained by registering an authentication callback with Google.

What are you doing here by the way? This code is the source for the site at http://lod-cloud.net/ there is no need to use this to submit datasets to the LOD cloud.

**Comment by frmichel** [comment]
Hey John, so yes indeed, while looking at the code I figured out what to put in that oauth2 file. But I still have a pb with the redirect url.
On the Google console I've declared an application and client ID, and I declared the following authorized redirect URLs:

    http://localhost:8080
    http://localhost:8080/add-dataset

And my oauth2 file is:
```
<client ID>
<secret>
http://localhost:8080/add-dataset
```

So now the authentication works fine I think, but I'm looping as I'm always getting back to the /add-dataset.
What redirect url should it be?


> What are you doing here by the way? This code is the source for the site at http://lod-cloud.net/ there is no need to use this to submit datasets to the LOD cloud.

This is actually related to the email I sent you yesterday about a possible API. I was willing to test if I can submit a dataset directly rather than having to fill in the web form.

**Comment by jmccrae** [comment]
The callback URL is http://lod-cloud.net/oauth2callback

I did not receive any emails from you yesterday.

**Comment by frmichel** [comment]
Ok, maybe I sent it to an old email address. Anyway here is what I was writing:

> In the context of the [D2KAB](http://d2kab.org/) research project, we would like to make it possible to submit datasets to the LOD cloud from [AgroPortal](http://agroportal.lirmm.fr/) which is a fork of BioPortal in the domains of agronomy, agriculture and biodiversity.
> We're talking ~100 datasets, hence the need to automate the submission process instead of having to fill in the web form manually.
> 
> Is there an HTTP API that would allow us to do that? If not, are there any plans of publishing such an API?
> 
> Any inputs welcome ;)
> Thx for your help,

**Comment by frmichel** [comment]
Ok thx.
