### ISSUE TITLE
API to submit a dataset to the LOD-cloud?

### ISSUE THREAD

**Issue by frmichel** [lod-cloud/lod-cloud-site#3]
Hi @jmccrae, following our exchange yesterday, here is the question I sent by email but maybe to an old email address. 

In the context of the [D2KAB](http://d2kab.org/) research project, we would like to make it possible to submit datasets to the LOD cloud from [AgroPortal](http://agroportal.lirmm.fr/) which is a fork of BioPortal in the domains of agronomy, agriculture and biodiversity.
We're talking ~100 datasets, hence the need to automate the submission process instead of having to fill in the web form manually.
 
Is there an HTTP API that would allow us to do that? If not, are there any plans of publishing such an API?
 
Any inputs welcome ;)
Thx for your help,

**Comment by jmccrae** [comment]
There are no plans to introduce an automatic API as there have been problems in the past with spam. I would accept bulk submissions by email (john@mccr.ae).

**Comment by frmichel** [comment]
> I would accept bulk submissions by email (john@mccr.ae).

@jmccrae, ok good to know. What format would you expect?

**Comment by jmccrae** [comment]
In the same JSON format as this file: https://lod-cloud.net/lod-data.json
