### ISSUE TITLE
How do you count the number of links to other datasets

### ISSUE THREAD

**Issue by gao-stu** [lod-cloud/lod-cloud-site#8]
Hi,how do you count the number of links to other datasets? I know these numbers are in mongodb, but how do you count these numbers . How do I count the number of links to other datasets for the dataset I want to submit

 best regards 

![1660560029191](https://user-images.githubusercontent.com/70122478/184622507-bd01a3a7-8bc0-4efe-b022-6ccb95216c48.png)

**Comment by jmccrae** [comment]
Links are provided by the contributors at lod-cloud.net, we don't verify the counts.
