### ISSUE TITLE
 Submit a dataset through website

### ISSUE THREAD

**Issue by hfsophie123** [lod-cloud/lod-cloud-site#9]
Hey [@jmccrae](https://github.com/jmccrae),I've just tried to submit a dataset through [submit button](https://lod-cloud.net/authorize?target=/add-dataset) but  I cannot manage to authenticate to submit  a dataset.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/5304501/192177422-5a7ff98c-f516-469c-897f-be722308be2b.png">

When I  get the "Login required" page, I select "Sign in with google", then I get an error from  https://accounts.google.com/signin/oauth/error saying :
Error 400 : redirect_uri_mismatch
![Uploading image.png…]()

How can I login and  submit a dataset?

**Comment by jmccrae** [comment]
We are experiencing some server stability issues and will fix this soon

**Comment by jmccrae** [comment]
Issue is fixed now,
